version: '3.7'
services:
    php:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                - APP_ENV=dev
        image: $APP_PHP_IMAGE_NAME
        container_name: $APP_PHP_CONTAINER_NAME
        user: "1000:1000"
        volumes:
            - .:/var/www/html/app
        environment:
            - APP_ENV
            - APP_VERSION            
